app:
  jwt-secret: sPT995aSWzGqXnoZT57coy6*&9mbNAO4mDK3ovqnOOfJsx9n0yoVUG
  ali-access-key: LTAI4GJYkkiLsALQGm44wk2y
  ali-secret: rQCopP9kCAz1ae4yxdjvaadBewTWUR
  j-push-app-key: XXXXXXXXXXXXXXXXX
  j-push-master-secret: XXXXXXXXXXXXXXXXX

spring:
  datasource:
    #url: jdbc:mysql://192.168.0.199:3306/qmlm?serverTimezone=Hongkong
    url: jdbc:mysql://mysql:3306/english_learning?serverTimezone=Hongkong
    username: springboot
    password: zIRxlmPZFFGngexqPlvgk^Ej
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name:
      # 设置为utf8mb4可解决emoj表情问题，同时数据库表字符集需要设置为utf8mb4
  #      connection-init-sql: "SET NAMES 'utf8mb4'"
  redis:
    host: redis
    lettuce:
      pool:
        max-active: 8
        max-wait: 2s
    database: 0
    port: 6379
    timeout: 4s
    password: frC4WcYuIPPgh5
  rabbitmq:
    addresses: mq:5672
    username: DtgarZ8g
    password: AELOJ01wZI7ZfpsR
    connection-timeout: 5s

logging:
  path: /cxylm/logs/api

