app:
  jwt-secret: sPT995aSWzGqXnoZT57coy6*&9mbNAO4mDK3ovqnOOfJsx9n0yoVUG
  ali-access-key: XXXXXXXXXXXXXXXXX
  ali-secret: XXXXXXXXXXXXXXXXX
  j-push-app-key: XXXXXXXXXXXXXXXXX
  j-push-master-secret: XXXXXXXXXXXXXXXXX

spring:
  datasource:
    url: jdbc:mysql://121.42.231.149:16953/english_learning?serverTimezone=Hongkong
    username: root
    password: 76qsnwuIC8lRnztP
    druid:
      filters: stat,wall,log4j
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 32
      pool-name:
      # 设置为utf8mb4可解决emoj表情问题，同时数据库表字符集需要设置为utf8mb4
#      connection-init-sql: "SET NAMES 'utf8mb4'"
  redis:
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms
    #password: guest
    database: 2
    port: 6379
    timeout: 10s
#    password: youmian

  rabbitmq:
    port: 5672
#    addresses: localhost:5672
#    virtual-host: /
#    username: hdkx
#    password: dev
#    connection-timeout: 5s

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            core: DEBUG
  path: /log/cxylm-api



